name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  Test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        run: Tests\RunTests.ps1
